sudo: false
language: python

matrix:
  include:
     - python: 2.7
     - python: 3.4
       allow_failures: true
     - python: 3.5
       allow_failures: true
     - python: 3.6
       allow_failures: true
     - python: 3.7
       allow_failures: true
       dist: xenial
     - python: 3.8-dev
       allow_failures: true
       dist: xenial
     - python: pypy
       allow_failures: true
     - python: pypy3.5
       allow_failures: true

install: pip install tox-travis
script: tox
